name: Python Package using Conda

on:
  push:
    branches:
      - main
  workflow_dispatch: {}


jobs:

  linux-mac-windows:
    name: ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        solver: ["libmamba"]
      max-parallel: 5
      
    environment: anaconda_build
  
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        environment-file: conda/environment.yml
        conda-solver: ${{ matrix.solver }}
        auto-activate-base: false
    - name: build
      run: |
        python -m pip install .
        cd bober/
        pyinstaller main.py --clean \
        --optimize 1 -F \
        -n Bober \
        --collect-all irods --collect-all bober \
        --exclude-module Pillow -w \
        --icon=./assets/icon.ico \
        --add-data=./assets/icon.ico:bober/assets/ \
        --add-data=./assets/bober/bober.png:bober/assets/bober/ \
        --add-data=./assets/loading-anim.gif:bober/assets/ \
        --add-data=./assets/i18n:bober/assets/i18n
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: Bober-build-${{ matrix.os }}
        path: bober/dist
