name: Python Package using Conda

on: [push, workflow_dispatch]


jobs:

  linux-mac:
    name: ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        solver: ["libmamba"]
      max-parallel: 5
      
    environment: anaconda_build
  
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        environment-file: conda/environment.yml
        conda-solver: ${{ matrix.solver }}
        auto-activate-base: false
    - name: build
      run: |
        python -m pip install .
        cd irodsgui/
        pyinstaller main.py -n irodsgui --collect-all irods --collect-all irodsgui -w
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: irodsgui-build-${{ matrix.os }}-${{ matrix.version }}
        path: irodsgui/dist
